//! Name lookups for API enums (tables generated by build.rs from the WIT files).

use pumpkin_plugin_api::player::{Particle, Sound, StatusEffectType};
use pumpkin_plugin_api::{Attribute, EntityType};

include!(concat!(env!("OUT_DIR"), "/nombres.rs"));

/// `minecraft:entity.player.levelup`, `generic.attack_damage`, `Jump-Boost` -> table key.
fn normalizar(nombre: &str) -> String {
    let nombre = nombre.to_lowercase();
    let nombre = nombre.strip_prefix("minecraft:").unwrap_or(&nombre);
    let nombre = nombre.strip_prefix("generic.").unwrap_or(nombre);
    nombre.replace(['.', '-'], "_")
}

pub fn buscar<T: Copy>(tabla: &[(&str, T)], nombre: &str) -> Option<T> {
    let clave = normalizar(nombre);
    tabla.iter().find(|(k, _)| *k == clave).map(|(_, v)| *v)
}

pub fn claves<'a, T>(tabla: &'a [(&'static str, T)]) -> impl Iterator<Item = &'static str> + 'a {
    tabla.iter().map(|(k, _)| *k)
}

pub fn sonido(n: &str) -> Option<Sound> {
    buscar(&SONIDOS, n)
}

/// Plays a sound with the vanilla /playsound command (the host's play_sound call traps
/// and kills the plugin on this server). Runs on the next tick, from the console, so
/// it's also outside whatever event is being handled. `para` is a player name or a
/// selector (`@a`: everyone nearby hears it). A wrong name just fails the command.
pub fn reproducir(nombre: &str, para: &str, (x, y, z): (f64, f64, f64), volumen: f32, tono: f32) {
    let nombre = nombre.to_lowercase();
    let nombre = nombre.strip_prefix("minecraft:").unwrap_or(&nombre);
    // `entity_player_levelup` (the tab-completion form) -> `entity.player.levelup`.
    let id = if nombre.contains('.') { nombre.to_string() } else { nombre.replace('_', ".") };
    let comando = format!("playsound minecraft:{id} player {para} {x:.2} {y:.2} {z:.2} {volumen} {tono}");
    pumpkin_plugin_api::scheduler::schedule_delayed_task(1, move |server| {
        server.execute_command(&comando, pumpkin_plugin_api::server::CommandSender::Console);
    });
}

pub fn particula(n: &str) -> Option<Particle> {
    buscar(&PARTICULAS, n)
}

pub fn efecto(n: &str) -> Option<StatusEffectType> {
    buscar(&EFECTOS, n)
}

pub fn atributo(n: &str) -> Option<Attribute> {
    buscar(&ATRIBUTOS, n)
}

pub fn entidad(n: &str) -> Option<EntityType> {
    buscar(&ENTIDADES, n)
}

/// `EntityType::MagmaCube` -> `minecraft:magma_cube`.
pub fn nombre_entidad(e: EntityType) -> Option<String> {
    ENTIDADES.iter().find(|(_, v)| *v == e).map(|(k, _)| format!("minecraft:{k}"))
}
